# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_comment_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_Form',
        ),
        migrations.AlterField(
            model_name='commentform',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 1)),
        ),
    ]
