# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_commentform_logged_inuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentform',
            name='logged_inuser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 6)),
        ),
    ]
