# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20160406_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 0, 58, 17, 188967, tzinfo=utc)),
        ),
    ]
