# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20160406_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='artForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 1, 22, 285623, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 1, 22, 285181, tzinfo=utc)),
        ),
    ]
