# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20160406_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedin',
            name='users',
        ),
        migrations.AlterField(
            model_name='artform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 3, 23, 89534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 3, 23, 89097, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='loggedin',
        ),
    ]
