# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20160406_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='artform',
            name='docfile',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='artform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 55, 41, 105005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 4, 55, 41, 104541, tzinfo=utc)),
        ),
    ]
