# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_auto_20160406_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('docfile', models.FileField(default='', upload_to='documents/%Y/%m/%d')),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 6, 7, 53, 50, 842230, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.DeleteModel(
            name='artForm',
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 7, 53, 50, 841756, tzinfo=utc)),
        ),
    ]
