# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_auto_20160407_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 1, 0, 49, 576877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 1, 0, 49, 576417, tzinfo=utc)),
        ),
    ]
