# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_auto_20160407_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 8, 1, 41, 46, 236480, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 1, 41, 46, 236004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 1, 41, 46, 235317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 8)),
        ),
    ]
