# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_auto_20160408_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_inuser', models.CharField(blank=True, max_length=30)),
                ('title', models.TextField(max_length=20)),
                ('notes', models.CharField(max_length=200)),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 21, 45, 406558, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 21, 45, 407060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 21, 45, 406051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 12)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 21, 45, 407528, tzinfo=utc)),
        ),
    ]
