# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_auto_20160412_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 33, 17, 302323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 33, 17, 301327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 33, 17, 301827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 6, 33, 17, 302778, tzinfo=utc)),
        ),
    ]
