# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0029_auto_20160412_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='logged_inuser',
            new_name='logged_user',
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 7, 46, 34, 336712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 7, 46, 34, 335757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 7, 46, 34, 336232, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 7, 46, 34, 337176, tzinfo=utc)),
        ),
    ]
