# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_auto_20160412_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.TextField(max_length=200)),
                ('projtype', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('joindate', models.CharField(max_length=200)),
                ('resume', models.FileField(default='', upload_to='documents/%Y/%m/%d')),
                ('JD', models.CharField(max_length=200)),
                ('logged_user', models.CharField(max_length=30)),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 13, 7, 44, 53, 542979, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 7, 44, 53, 541797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 7, 44, 53, 540754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 7, 44, 53, 541278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 13)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 7, 44, 53, 542278, tzinfo=utc)),
        ),
    ]
