# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_auto_20160414_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 35, 34, 503221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 35, 34, 502276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='JD',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 35, 34, 504287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 35, 34, 502746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 35, 34, 503660, tzinfo=utc)),
        ),
    ]
