# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_auto_20160414_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 38, 47, 183347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 38, 47, 182354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='JD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 38, 47, 184434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='joindate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 38, 47, 182856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 0, 38, 47, 183794, tzinfo=utc)),
        ),
    ]
