# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_auto_20160414_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='resume',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 26, 4, 732330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 26, 4, 731339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 26, 4, 733518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 26, 4, 731841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 1, 26, 4, 732809, tzinfo=utc)),
        ),
    ]
