# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0045_auto_20160414_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.TextField(max_length=200)),
                ('projtype', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('joindate', models.DateField()),
                ('resume', models.FileField(default='', upload_to='documents/%Y/%m/%d')),
                ('JD', models.CharField(max_length=200)),
                ('log_user', models.CharField(max_length=30)),
                ('dates', models.DateTimeField(default=datetime.datetime(2016, 4, 14, 6, 11, 43, 227273, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 6, 11, 43, 226176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 6, 11, 43, 225213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 6, 11, 43, 225691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 6, 11, 43, 226623, tzinfo=utc)),
        ),
    ]
